name: DEV CI

on:
  push:
    paths:
      - 'env/dev/config.json'
      - 'template.yaml'

  workflow_dispatch:

jobs:
  validate-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/setup-python@v5

      - name: Show Files
        run: ls -R

      - name: Validate DEV Config
        run: jq empty env/dev/config.json

      - name: Validate Template
        run: |
          python -c "import yaml; yaml.safe_load(open('template.yaml'))"

      - name: Simulate DEV
        run: echo "DEV workflow executed"