name: QA CI

on:
  push:
    paths:
      - 'env/qa/config.json'
      - 'template.yaml'

  workflow_dispatch:

jobs:
  validate-qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/setup-python@v5

      - name: Show Files
        run: ls -R

      - name: Validate QA Config
        run: jq empty env/qa/config.json

      - name: Validate Template
        run: |
          python -c "import yaml; yaml.safe_load(open('template.yaml'))"

      - name: Simulate QA
        run: echo "QA workflow executed"